//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octgn.UI.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Text() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Octgn.UI.Resources.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Connected.
        /// </summary>
        internal static string _Layout_Connected {
            get {
                return ResourceManager.GetString("_Layout_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Connection Status.
        /// </summary>
        internal static string _Layout_ConnectionStatus {
            get {
                return ResourceManager.GetString("_Layout_ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string _Layout_Disconnected {
            get {
                return ResourceManager.GetString("_Layout_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Host Game.
        /// </summary>
        internal static string _Layout_HostGame {
            get {
                return ResourceManager.GetString("_Layout_HostGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Game Name.
        /// </summary>
        internal static string _Layout_HostGame_GameName {
            get {
                return ResourceManager.GetString("_Layout_HostGame_GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string _Layout_NotConnected {
            get {
                return ResourceManager.GetString("_Layout_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reconnecting....
        /// </summary>
        internal static string _Layout_Reconnecting {
            get {
                return ResourceManager.GetString("_Layout_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There was an unknown error hosting the game.
        /// </summary>
        internal static string _Layout_UnknownHostingError {
            get {
                return ResourceManager.GetString("_Layout_UnknownHostingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Host.
        /// </summary>
        internal static string Global_Host {
            get {
                return ResourceManager.GetString("Global_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Join.
        /// </summary>
        internal static string Global_Join {
            get {
                return ResourceManager.GetString("Global_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Username.
        /// </summary>
        internal static string Global_Username {
            get {
                return ResourceManager.GetString("Global_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Game Name is Invalid.
        /// </summary>
        internal static string MainHub_GameNameInvalid {
            get {
                return ResourceManager.GetString("MainHub_GameNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There was an error hosting the game.
        /// </summary>
        internal static string MainHub_HostGame_UnhandledError {
            get {
                return ResourceManager.GetString("MainHub_HostGame_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your session is expired or invalid.
        /// </summary>
        internal static string MainHub_SessionError {
            get {
                return ResourceManager.GetString("MainHub_SessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The username provided is invalid.
        /// </summary>
        internal static string Models_Home_LoginModel_Username_Invalid {
            get {
                return ResourceManager.GetString("Models_Home_LoginModel_Username_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string Models_Home_LoginModel_Username_Required {
            get {
                return ResourceManager.GetString("Models_Home_LoginModel_Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Username must be between 2 and 24 characters long.
        /// </summary>
        internal static string Models_Home_LoginModel_Username_WrongLength {
            get {
                return ResourceManager.GetString("Models_Home_LoginModel_Username_WrongLength", resourceCulture);
            }
        }
    }
}
